<?php
/**
 * Daren theme setup.
 *
 * Daren is a block theme: the layout lives in templates/*.html, the design
 * system in theme.json (generated by .dev/build_theme.py), and the sections in
 * patterns/*.php. This file carries only what those cannot express — supports
 * flags, asset enqueues, block styles, pattern categories, and the files in
 * inc/ that give a few core blocks the behaviour the design needs.
 *
 * @package Daren
 */

defined( 'ABSPATH' ) || exit;

define( 'DAREN_VERSION', '1.0.0' );

/**
 * Theme supports.
 */
function daren_setup() {
	load_theme_textdomain( 'daren', get_template_directory() . '/languages' );

	add_theme_support( 'title-tag' );
	add_theme_support( 'post-thumbnails' );
	add_theme_support( 'automatic-feed-links' );
	add_theme_support( 'html5', array( 'search-form', 'comment-form', 'comment-list', 'gallery', 'caption', 'style', 'script' ) );
	add_theme_support( 'editor-styles' );
	add_theme_support( 'responsive-embeds' );
	add_theme_support( 'align-wide' );
	add_theme_support( 'wp-block-styles' );
	add_theme_support(
		'custom-logo',
		array(
			'height'      => 56,
			'width'       => 240,
			'flex-height' => true,
			'flex-width'  => true,
		)
	);

	// style.css is loaded into the editor canvas too, so cards, tabs and icons
	// look the same there as on the front end.
	add_editor_style( 'style.css' );
}
add_action( 'after_setup_theme', 'daren_setup' );

/**
 * Front-end styles.
 */
function daren_enqueue_styles() {
	wp_enqueue_style( 'daren-style', get_stylesheet_uri(), array(), DAREN_VERSION );
}
add_action( 'wp_enqueue_scripts', 'daren_enqueue_styles' );

/**
 * Block style variations.
 *
 * Registered here rather than in theme.json because a style needs a label for
 * the editor's Styles panel. The CSS behind each lives in style.css, which
 * always loads: a `style_handle` only enqueues while WordPress serves separate
 * core block assets, and any plugin can switch that off site-wide.
 */
function daren_register_block_styles() {
	$styles = array(
		'core/heading'   => array(
			array( 'daren-flag', __( 'Flagged title', 'daren' ) ),
		),
		'core/separator' => array(
			array( 'daren-band', __( 'Thick band', 'daren' ) ),
		),
		'core/group'     => array(
			array( 'daren-panel', __( 'Panel', 'daren' ) ),
		),
		'core/button'    => array(
			array( 'daren-arrow', __( 'With arrow', 'daren' ) ),
			array( 'daren-outline', __( 'Outline', 'daren' ) ),
		),
		'core/list'      => array(
			array( 'daren-rings', __( 'Ring bullets', 'daren' ) ),
		),
	);

	foreach ( $styles as $block => $variations ) {
		foreach ( $variations as $variation ) {
			list( $name, $label ) = $variation;
			register_block_style(
				$block,
				array(
					'name'  => $name,
					'label' => $label,
				)
			);
		}
	}
}
add_action( 'init', 'daren_register_block_styles' );

/**
 * The sticky header's shadow and the Share links.
 *
 * Deferred and in the footer: both are enhancements. Without the script the
 * header still sticks (that is CSS) and Share is a link to the post.
 */
function daren_enqueue_interactions() {
	wp_enqueue_script(
		'daren-interactions',
		get_template_directory_uri() . '/assets/js/interactions.js',
		array(),
		DAREN_VERSION,
		array(
			'in_footer' => true,
			'strategy'  => 'defer',
		)
	);

	wp_add_inline_script(
		'daren-interactions',
		'window.darenStrings = ' . wp_json_encode(
			array(
				'copied' => __( 'Link copied', 'daren' ),
			)
		) . ';',
		'before'
	);
}
add_action( 'wp_enqueue_scripts', 'daren_enqueue_interactions' );

/**
 * Pattern categories.
 */
function daren_register_pattern_categories() {
	$categories = array(
		'daren-posts'    => array(
			'label'       => __( 'Daren: story layouts', 'daren' ),
			'description' => __( 'Sections that list your posts: the banner, the checkerboard, cards and lists.', 'daren' ),
		),
		'daren-sections' => array(
			'label'       => __( 'Daren: sections', 'daren' ),
			'description' => __( 'Full-width sections for building pages.', 'daren' ),
		),
		'daren-pages'    => array(
			'label'       => __( 'Daren: pages', 'daren' ),
			'description' => __( 'Complete page layouts.', 'daren' ),
		),
	);

	foreach ( $categories as $slug => $args ) {
		register_block_pattern_category( $slug, $args );
	}
}
add_action( 'init', 'daren_register_pattern_categories' );

/**
 * Expand shortcodes in shortcode blocks inside templates.
 *
 * core/shortcode's render callback only runs wpautop(); the expansion normally
 * comes from do_shortcode on `the_content`, which never runs for a block
 * template. Without this the contact template would print `[daren_contact_form]`.
 * do_shortcode on already-expanded output is a no-op, so this is safe everywhere.
 *
 * @param string $content Rendered block.
 * @return string
 */
function daren_render_shortcode_block( $content ) {
	return do_shortcode( $content );
}
add_filter( 'render_block_core/shortcode', 'daren_render_shortcode_block' );

require get_template_directory() . '/inc/front-page-setup.php';
require get_template_directory() . '/inc/blocks.php';
require get_template_directory() . '/inc/contact.php';
require get_template_directory() . '/inc/newsletter.php';
require get_template_directory() . '/inc/forms.php';
require get_template_directory() . '/inc/woocommerce.php';
require get_template_directory() . '/inc/scheme.php';
require get_template_directory() . '/inc/updates.php';
